### ISSUE TITLE
New intercom.io SDK 2.0

### ISSUE THREAD

**Issue by inakiabt** [simonrand/TiIntercom#1]
https://github.com/intercom/intercom-ios/releases/tag/2.0.0
This version adds better in-app messaging https://www.intercom.io/in-app-messaging

Docs:
- http://docs.intercom.io/install-on-your-mobile-product/configure-the-ios-sdk
- http://docs.intercom.io/install-on-your-mobile-product/install-the-intercom-ios-sdk

I'd love to use it in this great Titanium module +1

**Comment by simonrand** [comment]
Saw this today..

Unfortunately my time is very tight at the moment, and I'm no longer using this module in any production app, so my capacity to update this very limited – on quick look it looks like it may be a relatively straightforward update –  it might be a while before I get to it so if someone else had the capacity to start this that would be great?

**Comment by markive** [comment]
We released an updated version that you can use: https://github.com/markive/TiIntercom

**Comment by simonrand** [comment]
Nice @markive – am going to close this so..
